# Generated by Django 5.0.6 on 2024-08-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('property_name', models.CharField(max_length=200)),
                ('property_description', models.CharField(max_length=200)),
                ('property_location', models.CharField(max_length=250)),
            ],
        ),
    ]
