# Generated by Django 5.0.6 on 2024-08-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='available_property',
            field=models.CharField(choices=[('Available', 'available'), ('Sold', 'sold')], default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_description',
            field=models.CharField(max_length=250),
        ),
    ]
