# Generated by Django 5.0.6 on 2024-08-14 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties_app', '0002_property_available_property_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='available_property',
            new_name='property_status',
        ),
    ]
