# Generated by Django 5.0.6 on 2024-08-14 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties_app', '0003_rename_available_property_property_property_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='property_status',
            new_name='available_property',
        ),
    ]
