# Generated by Django 5.0.6 on 2024-08-14 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_interested_app', '0003_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
