# Generated by Django 5.0.6 on 2024-08-15 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_newuser_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewUser',
        ),
    ]
