# Generated by Django 5.0.6 on 2024-08-13 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties_app', '0001_initial'),
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseProperty',
            fields=[
                ('purchase_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties_app.property')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.user')),
            ],
        ),
    ]
